# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Sarah Jane Schmidt
email: sjschmidt@aip.de
description: > # this means to ignore newlines until "url:"
  Professional site of Sarah Jane Schmidt.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> using the <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

url:  # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: 10 Oct 2019 # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: sjschmidt # your GitHub user name
twitter_username: sjs917 # your Twitter handle
linkedin_username: sarah-schmidt-2ba01975 # your LinkedIn user name
scholar_userid: # your Google Scholar ID
orcid_id: 0000-0002-7224-7702 # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username

contact_note: >
  Get in touch! It's fastest to find me on twitter or send me an email. 

google_analytics: UA-147426691-1 # put your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: blog
blog_description: perhaps updated occassionally

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  iprojects:
    output: true
    permalink: /iprojects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Schmidt

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"

